### ISSUE TITLE
答题

### ISSUE THREAD

**Issue by 1563dfghjm** [qin1127/zhihuishu#2]
大佬，答题部分的参数怎么搞，求大佬出一个答题部分的

**Comment by RichY0608** [comment]
有答题功能了？

**Comment by 1563dfghjm** [comment]
没解决，进入考试没解决（app端的）

**Comment by RichY0608** [comment]
测验的能完成？章节测验

**Comment by 1563dfghjm** [comment]
嗯嗯，就是加密有点难

**Comment by RichY0608** [comment]
打包好的 登录好了就可以了是吧 视频 章节测试  现在就不能考试呗

**Comment by 1563dfghjm** [comment]
差一个接口，就开始考试那个，那个没弄，还有一个就是开始考试那里会有点选验证码，参数没搞明白，倒是训练了点选模型

**Comment by RichY0608** [comment]
不急慢慢 调试 还没选课呢

**Comment by 1563dfghjm** [comment]
你这，.....

**Comment by RichY0608** [comment]
登录不上啊 乱码了

**Comment by RichY0608** [comment]
![Uploading 17096357320393850747339213153069.jpg…]()

**Comment by Bao-qing** [comment]
图片看不到啊，我的问题吗

**Comment by Bao-qing** [comment]
答题有点难搞😖

**Comment by RichY0608** [comment]
> 答题有点难搞😖

![Uploading 1709690020320582180717731173285.jpg…]()

**Comment by RichY0608** [comment]
> 图片看不到啊，我的问题吗

Traceback (most recent call last):
  File "gui-log.py", line 1438, in <module>
  File "gui-log.py", line 739, in __init__
  File "execjs\_abstract_runtime_context.py", line 37, in call
  File "execjs\_external_runtime.py", line 92, in _call
  File "execjs\_external_runtime.py", line 78, in _eval
  File "execjs\_abstract_runtime_context.py", line 18, in exec_
  File "execjs\_external_runtime.py", line 88, in _exec_
  File "execjs\_external_runtime.py", line 171, in _extract_result
execjs._exceptions.ProgramError: SyntaxError: 缺少标识符

**Comment by 1563dfghjm** [comment]
那把慢刷习惯分分的逻辑写一下嘛大佬，还有互动分，见面课

**Comment by RichY0608** [comment]
> 那把慢刷习惯分分的逻辑写一下嘛大佬，还有互动分，见面课

你测验写好的给我发一下

**Comment by 1563dfghjm** [comment]
咱私聊

**Comment by RichY0608** [comment]
联系方式发一下

**Comment by 1563dfghjm** [comment]
17387822016

**Comment by 1563dfghjm** [comment]
sx2070859017

**Comment by Bao-qing** [comment]
> > 图片看不到啊，我的问题吗
> 
> 回溯（最近一次调用）：文件“gui-log.py”，第 1438 行，在文件“gui-log.py”中，第 739 行，**在 init** 中 文件“execjs_abstract_runtime_context.py”，第 37 行，在调用中 文件“execjs_external_runtime.py”，第 92 行，在 _call 中 文件“execjs_external_runtime.py”，第 78 行，在 _eval 中 文件“execjs_abstract_runtime_context.py”，第 18 行，在 exec_ 文件中 文件“execjs_external_runtime.py”，第 88 行， 在 _exec_ 文件“execjs_external_runtime.py”中，第 171 行，在 _extract_result execjs._exceptions中。ProgramError： SyntaxError： 缺少标识符

装nodejs了吗？

**Comment by Bao-qing** [comment]
> 那把慢刷习惯分分的逻辑写一下嘛大佬，还有互动分，见面课

行，我试试吧，我也是小白，还在学习

**Comment by 1563dfghjm** [comment]
大佬威武，可以私聊嘛

**Comment by Bao-qing** [comment]
QQ 919836565
