### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by helloshuaihui** [qin1127/zhihuishu#5]
不能登录，提示登录失败出现未知错误

**Comment by Bao-qing** [comment]
把这个文件发给我看看吧，邮箱919836565@qq.com
<img width="474" alt="Image_1713001032667" src="https://github.com/qin1127/zhihuishu/assets/125798142/0a8b7b3e-de28-45d7-be9a-e53cbba95159">

**Comment by helloshuaihui** [comment]
邮件已经发你，请查收

**Comment by manzeyu-6** [comment]
我也是登陆不了
C:\Users\16552\Desktop\新建文件夹\zhihuishu-main>python main.py
获取用户名和密码失败
登录窗口： ******* *******
读取配置失败
Traceback (most recent call last):
  File "C:\Users\16552\Desktop\新建文件夹\zhihuishu-main\main.py", line 746, in <module>
    capt_cha = Captcha(captcha_id, captcha_referer)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16552\Desktop\新建文件夹\zhihuishu-main\captcha\captcha.py", line 23, in __init__
    self.captchar_conf = self.get_captcha()
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\16552\Desktop\新建文件夹\zhihuishu-main\captcha\captcha.py", line 151, in get_captcha
    if response_data['data']["type"] == 2:
       ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'
